version: "3.8"

services:
  app:
    build:
      context: ./swstarter-app
      dockerfile: ./Dockerfile
      no_cache: false
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://backend:3001/api
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./swstarter-backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SWAPI_BASE_URL=https://swapi.info/api
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/lawnstarter
      - STATS_JOB_INTERVAL_MINUTES=5
    restart: always
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=lawnstarter

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: always

volumes:
  redis_data:
  mongodb_data:
